Web/Controllers/FundraisingEventController.cs
using Domain.Models;
using Newtonsoft.Json;
using Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Web.Models;
using Web.RestClients;
using Web.Helpers;
using System.Collections;

namespace Web.Controllers
{
    public class FundraisingEventController : Controller
    {
        FundraisingEventService fs = new FundraisingEventService();
        FundraisingEventRestClient frc = new FundraisingEventRestClient();
        CampService cs = new CampService();
        // GET: FundraisingEvent
        public ActionResult Index()
        {
            if (Session["idUser"] == null)
                return RedirectToAction("Login", "Home");
            ViewBag.eventCountByCountry = frc.eventCountByCountry();
            ViewBag.avgCompletionEvent=frc.avgCompletionEvent();
            var events = fs.GetAll();
            IEnumerable <long> id = events.Select(f => f.id);
            long idd = events.FirstOrDefault().id;
            string val = string.Join("," + Environment.NewLine,
            frc.eventCountByCountry().Select(d => "['" + d.Key + "', " + d.Value + "]"));
            ViewBag.val = val;
            return View(events);
        }
        
        public ActionResult getAllEventsForClient()
        {
            var Events = frc.getAllEvents();
            return View(Events);
        }
        public ActionResult getFinishedEventsForClient()
        {
            var Events = frc.getFinishedEvents();
            return View(Events);
        }
        public ActionResult getInProgressEventsForClient()
        {
            var Events = frc.getEventsInProgress();
            return View(Events);
        }
        public ActionResult getLowStateEvents()
        {
            var Events = frc.getLOWStateEvents();
            return View(Events);
        }
        public ActionResult getMediumStateEvents()
        {
            var Events = frc.getMediumStateEvents();
            return View(Events);
        }
        public ActionResult getHighStateEvents()
        {
            var Events = frc.getHIGHStateEvents();
            return View(Events);
        }
        public ActionResult statsForClient()
        {
            ViewBag.eventCountByCountry = frc.eventCountByCountry();
            ViewBag.avgCompletionEvent = frc.avgCompletionEvent();
            ViewBag.eventCountByMonth = frc.eventCountByMonthThisYear();
            return View();
        }


        public ActionResult getAll()
        {
            if (Session["idUser"] == null)
                return RedirectToAction("Login", "Home");

            var Events = frc.getAllEvents();
            return View(Events);
        }
        
        public ActionResult getByUser()
        {
            if (Session["idUser"] == null)
                return RedirectToAction("Login", "Home");
            IEnumerable<fundraisingevent> f = fs.GetEventsByUser((long)Session["idUser"]);
            return View(f);
        }
        // GET: FundraisingEvent/Details/5
        public ActionResult Details(int id)
        {
            if (Session["idUser"] == null)
                return RedirectToAction("Login", "Home");
            var s = fs.GetById(id);
            ViewBag.sumAmount = frc.getSumAmountDonationByEvent(id);
            return View(s);

        }
        // GET: FundraisingEvent/DetailsEventForClient/5
        public ActionResult DetailsEventForClient(int id)
        {
            var s = fs.GetById(id);
            ViewBag.sumAmount  = frc.getSumAmountDonationByEvent(id);
            /*long avg = ((ViewBag.sumAmount) * 100)/s.goal;
            ViewBag.avg = avg;*/
            return View(s);

        }

        // GET: FundraisingEvent/Create
        public ActionResult Create()
        {
            if(Session["idUser"]==null)
                return RedirectToAction("Login", "Home");
            var list = new List<SelectListItem>
            {
                new SelectListItem {Text = "low", Value = "LOW"},
                new SelectListItem {Text = "medium", Value = "MEDIUM"},
                new SelectListItem {Text = "high", Value = "HIGH"}
            };

            ViewData["list"] = list;
            FundraisingEventModel fm = new FundraisingEventModel();
            fm.camp = cs.GetAll().ToSelectListItem();
            return View(fm);
            
        }

        // POST: FundraisingEvent/Create
        [HttpPost]
        public ActionResult Create(FundraisingEventModel fm, HttpPostedFileBase Image)
        {
            if (!ModelState.IsValid || Image == null || Image.ContentLength == 0)
            {
                RedirectToAction("Create");
            }
            fm.imagePath = Image.FileName;
            try
            {
                frc.addEvent(fm, (string)Session["token"], Convert.ToInt32(Session["idUser"]));
                var path = Path.Combine(Server.MapPath("~/Content/Upload/"), Image.FileName);
                Image.SaveAs(path);
                return RedirectToAction("getByUser");
            }
            catch(NullReferenceException)
            {
                
                return View(fm);
            }
        }

        // GET: FundraisingEvent/Edit/5
        public ActionResult Edit(long id)
        {
            if (Session["idUser"] == null)
                return RedirectToAction("Login", "Home");

            //var s = frc.getEventById(id);
             var s = fs.GetById(id);
            FundraisingEventModel fm = new FundraisingEventModel { };
            fm.id = s.id;
            fm.title = s.title;
            fm.description = s.description;
            fm.camp_id = s.camp_id;
            fm.finishingDate = s.finishingDate;
            fm.state = s.state;
            fm.urgency = s.urgency;
            fm.imagePath = s.imagePath;
            fm.publishDate = s.publishDate;
            fm.publisher_id = s.publisher_id;
            fm.goal = s.goal;
            return View(fm);

        }

        // POST: FundraisingEvent/Edit/5
        [HttpPost]
        public ActionResult Edit(FundraisingEventModel fm)
        {

            try
            {
                frc.editEvent(fm, (string)Session["token"], Convert.ToInt32(Session["idUser"]));
                
                return RedirectToAction("getAll");
            }
            catch //(Exception e)
            {
                return View();
                /*throw;
                return RedirectToAction("Edit");*/
            }
        }

        // GET: FundraisingEvent/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FundraisingEvent/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Web/Views/FundraisingEvent/Create.cshtml
@model Web.Models.FundraisingEventModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "FundraisingEvent", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FundraisingEventModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.goal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.goal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.goal, "", new { @class = "text-danger" })
            </div>
        </div>

        

        
        <div class="form-group">
            @Html.LabelFor(model => model.imagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Image", null, new { type = "file" })
                @Html.ValidationMessageFor(model => model.imagePath)
            </div>
        </div>
        

        <div class="form-group">
            @Html.LabelFor(model => model.urgency, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.urgency, ViewData["list"] as List<SelectListItem>, "--Select Urgency--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.urgency, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.camp_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model=> model.camp_id,Model.camp)
                
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-primary" type="button">@Html.ActionLink("Back to List", "getAll")</button>
                <button class="btn btn-primary" type="reset">Reset</button>
                <input type="submit" value="Create" class="btn btn-success" />
                
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/FundraisingEvent/getAll.cshtml
@model IEnumerable<Domain.Models.fundraisingevent>

@{
    ViewBag.Title = "getAll";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>getAll</h2>
<p>
    @Html.ActionLink("Add New event", "Create")
</p>

<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Fundraising events </h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <div class="row">

                    <p>All events</p>




                    @foreach (var item in Model)
                    {

                        <div class="col-md-55">
                            <div class="thumbnail">
                                <div class="image view view-first">
                                    <img style="width: 100%; display: block;" src="@Url.Content("~/Content/Upload/"+item.imagePath)" alt="eventimage" />
                                    <div class="mask no-caption">
                                        <div class="tools tools-bottom">
                                            <a href="@Url.Action("Details", "FundraisingEvent",new { id = item.id })"><i class="fa fa-link"></i></a>
                                            <a href="@Url.Action("Edit", "FundraisingEvent",new { id = item.id })"><i class="fa fa-pencil"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="caption">
                                    <p>
                                        <strong>@item.title</strong>
                                    </p>
                                    <p>@item.description</p>

                                </div>
                            </div>
                        </div>
                    }




                </div>
            </div>
        </div>
    </div>
</div>

Web/Views/FundraisingEvent/getAllEventsForClient.cshtml
@model IEnumerable<Domain.Models.fundraisingevent>

@{
    ViewBag.Title = "getAllEventsForClient";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}

<section class="latest-causes-section">
    <div class="auto-container">

        <div class="row clearfix">
            <!--Default Cause Box-->
            <!--Default Cause Box-->
            <!--Default Cause Box-->
            @foreach (var item in Model)
            {

                <div class="default-cause-box col-md-4 col-sm-6 col-xs-12">
                    <div class="inner-box wow fadeIn" data-wow-delay="1000ms" data-wow-duration="1500ms">
                        <div class="image-box">
                            <div class="image">
                                <img src="@Url.Content("~/Content/Upload/" + item.imagePath)" alt="" width="100" height="100" />
                                <div class="overlay-box">
                                    <a href="@Url.Action("DetailsEventForClient", "FundraisingEvent", new { id = item.id })" class="search-btn"><span class="icon fa fa-link"></span></a>
                                </div>
                            </div>
                        </div>
                        <div class="lower-content">
                            <h3><a href="@Url.Action("DetailsEventForClient", "FundraisingEvent", new { id = item.id })">@item.title</a></h3>
                            <div class="text">@item.description</div>


                            <!--donate info-->
                            <div class="donate-info clearfix">

                                <div class="amount goal">GOAL: $@item.goal</div>
                            </div>

                        </div>
                    </div>
                </div>}

        </div>

        <!-- Styled Pagination -->
        
        <br>
    </div>
</section>
<!--End Latest Causes Section-->
<!--Subscribe Style One-->
<section class="subscribe-style-one" style="background-image:url(images/background/patten-1.png);">
    <div class="auto-container">
        <div class="row clearfix">
            <div class="column col-md-7 col-sm-6 col-xs-12">
                <h2>SUBSCRIBE FOR NEWSLETTER</h2>
                <div class="text">Lorem ipsum dolor sit amet, quo odio atqui tamquam eu, duo ex amet elitr.</div>
            </div>
            <div class="column col-md-5 col-sm-6 col-xs-12 text-right">
                <form method="post" action="contact.html">
                    <div class="form-group">
                        <input type="email" name="email" value="" placeholder="Email" required>
                        <button type="submit" class="theme-btn btn-style-one">Subscribe</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

Web/Views/FundraisingEvent/getByUser.cshtml
@model IEnumerable<Domain.Models.fundraisingevent>

@{
    ViewBag.Title = "getByUser";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<p>
    @Html.ActionLink("Add new fundraising event", "Create")
</p>


<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Fundraising events </h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <div class="row">

                    <p>My events</p>

                    
                    
                   
                    @foreach (var item in Model)
                    {

                    <div class="col-md-55">
                        <div class="thumbnail">
                            <div class="image view view-first">
                                <img style="width: 100%; display: block;" src="@Url.Content("~/Content/Upload/"+item.imagePath)" alt="eventimage" />
                                <div class="mask no-caption">
                                    <div class="tools tools-bottom">
                                        <a href="@Url.Action("Details", "FundraisingEvent",new { id = item.id })"><i class="fa fa-link"></i></a>
                                        <a href="@Url.Action("Edit", "FundraisingEvent",new { id = item.id })"><i class="fa fa-pencil"></i></a>
                                    </div>
                                </div>
                            </div>
                            <div class="caption">
                                <p>
                                    <strong>@item.title</strong>
                                </p>
                                <p>@item.description</p>
                                
                            </div>
                        </div>
                    </div>
                    }



                 
                </div>
            </div>
        </div>
    </div>
</div>
         

Web/Views/FundraisingEvent/getFinishedEventsForClient.cshtml
@model IEnumerable<Domain.Models.fundraisingevent>

@{
    ViewBag.Title = "getFinishedEventsForClient";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}

<section class="latest-causes-section">
    <div class="auto-container">

        <div class="row clearfix">
            <!--Default Cause Box-->
            <!--Default Cause Box-->
            <!--Default Cause Box-->
            @foreach (var item in Model)
            {

                <div class="default-cause-box col-md-4 col-sm-6 col-xs-12">
                    <div class="inner-box wow fadeIn" data-wow-delay="1000ms" data-wow-duration="1500ms">
                        <div class="image-box">
                            <div class="image">
                                <img src="@Url.Content("~/Content/Upload/" + item.imagePath)" alt="" width="100" height="100" />
                                <div class="overlay-box">
                                    <a href="@Url.Action("DetailsEventForClient", "FundraisingEvent", new { id = item.id })" class="search-btn"><span class="icon fa fa-link"></span></a>
                                </div>
                            </div>
                        </div>
                        <div class="lower-content">
                            <h3><a href="@Url.Action("DetailsEventForClient", "FundraisingEvent", new { id = item.id })">@item.title</a></h3>
                            <div class="text">@item.description</div>

                            
                            <!--donate info-->
                            <div class="donate-info clearfix">
                                
                                <div class="amount goal">GOAL: $@item.goal</div>
                            </div>

                        </div>
                    </div>
                </div>}

        </div>

        <!-- Styled Pagination -->
        
        <br>
    </div>
</section>
<!--End Latest Causes Section-->
<!--Subscribe Style One-->
<section class="subscribe-style-one" style="background-image:url(images/background/patten-1.png);">
    <div class="auto-container">
        <div class="row clearfix">
            <div class="column col-md-7 col-sm-6 col-xs-12">
                <h2>SUBSCRIBE FOR NEWSLETTER</h2>
                <div class="text">Lorem ipsum dolor sit amet, quo odio atqui tamquam eu, duo ex amet elitr.</div>
            </div>
            <div class="column col-md-5 col-sm-6 col-xs-12 text-right">
                <form method="post" action="contact.html">
                    <div class="form-group">
                        <input type="email" name="email" value="" placeholder="Email" required>
                        <button type="submit" class="theme-btn btn-style-one">Subscribe</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

Web/Views/FundraisingEvent/getHighStateEvents.cshtml
@model IEnumerable<Domain.Models.fundraisingevent>

@{
    ViewBag.Title = "getHighStateEvents";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}


<section class="latest-causes-section">
    <div class="auto-container">

        <div class="row clearfix">
            <!--Default Cause Box-->
            <!--Default Cause Box-->
            <!--Default Cause Box-->
            @foreach (var item in Model)
            {

                <div class="default-cause-box col-md-4 col-sm-6 col-xs-12">
                    <div class="inner-box wow fadeIn" data-wow-delay="1000ms" data-wow-duration="1500ms">
                        <div class="image-box">
                            <div class="image">
                                <img src="@Url.Content("~/Content/Upload/" + item.imagePath)" alt="" width="100" height="100" />
                                <div class="overlay-box">
                                    <a href="@Url.Action("DetailsEventForClient", "FundraisingEvent", new { id = item.id })" class="search-btn"><span class="icon fa fa-link"></span></a>
                                </div>
                            </div>
                        </div>
                        <div class="lower-content">
                            <h3><a href="@Url.Action("DetailsEventForClient", "FundraisingEvent", new { id = item.id })">@item.title</a></h3>
                            <div class="text">@item.description</div>


                            <!--donate info-->
                            <div class="donate-info clearfix">

                                <div class="amount goal">GOAL: $@item.goal</div>
                            </div>

                        </div>
                    </div>
                </div>}

        </div>

        <!-- Styled Pagination -->
        
        <br>
    </div>
</section>
<!--End Latest Causes Section-->
<!--Subscribe Style One-->
<section class="subscribe-style-one" style="background-image:url(images/background/patten-1.png);">
    <div class="auto-container">
        <div class="row clearfix">
            <div class="column col-md-7 col-sm-6 col-xs-12">
                <h2>SUBSCRIBE FOR NEWSLETTER</h2>
                <div class="text">Lorem ipsum dolor sit amet, quo odio atqui tamquam eu, duo ex amet elitr.</div>
            </div>
            <div class="column col-md-5 col-sm-6 col-xs-12 text-right">
                <form method="post" action="contact.html">
                    <div class="form-group">
                        <input type="email" name="email" value="" placeholder="Email" required>
                        <button type="submit" class="theme-btn btn-style-one">Subscribe</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

Web/Views/FundraisingEvent/getInProgressEventsForClient.cshtml
@model IEnumerable<Domain.Models.fundraisingevent>

@{
    ViewBag.Title = "getInProgressEventsForClient";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}

<section class="latest-causes-section">
    <div class="auto-container">

        <div class="row clearfix">
            <!--Default Cause Box-->
            <!--Default Cause Box-->
            <!--Default Cause Box-->
            @foreach (var item in Model)
            {

                <div class="default-cause-box col-md-4 col-sm-6 col-xs-12">
                    <div class="inner-box wow fadeIn" data-wow-delay="1000ms" data-wow-duration="1500ms">
                        <div class="image-box">
                            <div class="image">
                                <img src="@Url.Content("~/Content/Upload/" + item.imagePath)" alt="" width="100" height="100" />
                                <div class="overlay-box">
                                    <a href="@Url.Action("DetailsEventForClient", "FundraisingEvent", new { id = item.id })" class="search-btn"><span class="icon fa fa-link"></span></a>
                                </div>
                            </div>
                        </div>
                        <div class="lower-content">
                            <h3><a href="@Url.Action("DetailsEventForClient", "FundraisingEvent", new { id = item.id })">@item.title</a></h3>
                            <div class="text">@item.description</div>


                            <!--donate info-->
                            <div class="donate-info clearfix">

                                <div class="amount goal">GOAL: $@item.goal</div>
                            </div>

                        </div>
                    </div>
                </div>}

        </div>

        <!-- Styled Pagination -->
        
        <br>
    </div>
</section>
<!--End Latest Causes Section-->
<!--Subscribe Style One-->
<section class="subscribe-style-one" style="background-image:url(images/background/patten-1.png);">
    <div class="auto-container">
        <div class="row clearfix">
            <div class="column col-md-7 col-sm-6 col-xs-12">
                <h2>SUBSCRIBE FOR NEWSLETTER</h2>
                <div class="text">Lorem ipsum dolor sit amet, quo odio atqui tamquam eu, duo ex amet elitr.</div>
            </div>
            <div class="column col-md-5 col-sm-6 col-xs-12 text-right">
                <form method="post" action="contact.html">
                    <div class="form-group">
                        <input type="email" name="email" value="" placeholder="Email" required>
                        <button type="submit" class="theme-btn btn-style-one">Subscribe</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

Web/Views/FundraisingEvent/getLowStateEvents.cshtml
@model IEnumerable<Domain.Models.fundraisingevent>

@{
    ViewBag.Title = "getLowStateEvents";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}

<section class="latest-causes-section">
    <div class="auto-container">

        <div class="row clearfix">
            <!--Default Cause Box-->
            <!--Default Cause Box-->
            <!--Default Cause Box-->
            @foreach (var item in Model)
            {

                <div class="default-cause-box col-md-4 col-sm-6 col-xs-12">
                    <div class="inner-box wow fadeIn" data-wow-delay="1000ms" data-wow-duration="1500ms">
                        <div class="image-box">
                            <div class="image">
                                <img src="@Url.Content("~/Content/Upload/" + item.imagePath)" alt="" width="100" height="100" />
                                <div class="overlay-box">
                                    <a href="@Url.Action("DetailsEventForClient", "FundraisingEvent", new { id = item.id })" class="search-btn"><span class="icon fa fa-link"></span></a>
                                </div>
                            </div>
                        </div>
                        <div class="lower-content">
                            <h3><a href="@Url.Action("DetailsEventForClient", "FundraisingEvent", new { id = item.id })">@item.title</a></h3>
                            <div class="text">@item.description</div>


                            <!--donate info-->
                            <div class="donate-info clearfix">

                                <div class="amount goal">GOAL: $@item.goal</div>
                            </div>

                        </div>
                    </div>
                </div>}

        </div>

        <!-- Styled Pagination -->
        
        <br>
    </div>
</section>
<!--End Latest Causes Section-->
<!--Subscribe Style One-->
<section class="subscribe-style-one" style="background-image:url(images/background/patten-1.png);">
    <div class="auto-container">
        <div class="row clearfix">
            <div class="column col-md-7 col-sm-6 col-xs-12">
                <h2>SUBSCRIBE FOR NEWSLETTER</h2>
                <div class="text">Lorem ipsum dolor sit amet, quo odio atqui tamquam eu, duo ex amet elitr.</div>
            </div>
            <div class="column col-md-5 col-sm-6 col-xs-12 text-right">
                <form method="post" action="contact.html">
                    <div class="form-group">
                        <input type="email" name="email" value="" placeholder="Email" required>
                        <button type="submit" class="theme-btn btn-style-one">Subscribe</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>